trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Terraform/Day13/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - Terraform/Day13/**

variables:
  - template: pipelines/vars/centralindia.yml

stages:
  - stage: Init
    displayName: Terraform Init
    jobs:
      - job: TerraformInit
        displayName: Initialize Backend
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: pipelines/templates/tf-init.yml

  - stage: Plan
    displayName: Terraform Plan
    dependsOn: Init
    jobs:
      - job: TerraformPlan
        displayName: Plan Infrastructure
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: pipelines/templates/tf-plan.yml

  - stage: Apply
    displayName: Terraform Apply
    dependsOn: Plan
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: TerraformApply
        displayName: Apply Infrastructure
        environment: day13-monitoring
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - template: pipelines/templates/tf-apply.yml
